# Generated by Django 4.2.4 on 2023-08-01 20:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('Nome', models.CharField(max_length=100)),
                ('Matricula', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999)])),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1)),
                ('Data_Nascimento', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('Renda', models.CharField(choices=[('0', '0'), ('Até R$ 1.000', 'Até R$ 1.000'), ('R$ 1.001 a R$ 2.000', 'R$ 1.001 a R$ 2.000'), ('R$ 2.001 a R$ 3.000', 'R$ 2.001 a R$ 3.000'), ('R$ 3.001 a R$ 4.000', 'R$ 3.001 a R$ 4.000'), ('R$ 4.001 a R$ 5.000', 'R$ 4.001 a R$ 5.000'), ('R$ 5.001 a R$ 6.000', 'R$ 5.001 a R$ 6.000'), ('R$ 6.001 a R$ 7.000', 'R$ 6.001 a R$ 7.000'), ('R$ 7.001 a R$ 8.000', 'R$ 7.001 a R$ 8.000'), ('R$ 8.001 a R$ 9.000', 'R$ 8.001 a R$ 9.000'), ('R$ 9.001 a R$ 10.000', 'R$ 9.001 a R$ 10.000'), ('R$ 10.001 a R$ 15.000', 'R$ 10.001 a R$ 15.000'), ('R$ 15.001 a R$ 20.000', 'R$ 15.001 a R$ 20.000'), ('R$ 20.001 a R$ 30.000', 'R$ 20.001 a R$ 30.000'), ('R$ 30.001 a R$ 50.000', 'R$ 30.001 a R$ 50.000'), ('Acima de R$ 50.000', 'Acima de R$ 50.000')], default='0', max_length=25)),
                ('Mora_Com_Pais', models.BooleanField(default=False)),
                ('Trabalha', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
                ('Quantidade_Filhos', models.IntegerField(default=0)),
                ('Raca', models.CharField(choices=[('BRANCO', 'Branco'), ('PRETO', 'Preto'), ('PARDO', 'Pardo'), ('INDIGENA', 'Indígena'), ('AMARELO', 'Amarelo')], default='BRANCO', max_length=20)),
                ('Estado_Civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], default='Solteiro', max_length=20)),
                ('Responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.responsavel')),
            ],
        ),
    ]
