# Generated by Django 4.2.4 on 2023-08-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Renda',
            new_name='Renda_Própria',
        ),
    ]
