# Generated by Django 4.2.4 on 2023-08-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_renda_aluno_renda_própria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Matricula',
            new_name='Matrícula',
        ),
    ]
