# Generated by Django 4.2.4 on 2023-08-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_aluno_autorizo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Renda_Própria',
            field=models.CharField(choices=[('Até R$ 1.000', 'Até R$ 1.000'), ('R$ 1.001 a R$ 3.000', 'R$ 1.001 a R$ 3.000'), ('R$ 3.001 a R$ 5.000', 'R$ 3.001 a R$ 5.000'), ('R$ 5.001 a R$ 7.000', 'R$ 5.001 a R$ 7.000'), ('R$ 7.001 a R$ 10.000', 'R$ 7.001 a R$ 10.000'), ('R$ 10.001 a R$ 15.000', 'R$ 10.001 a R$ 15.000'), ('Acima de R$ 15.001', 'Acima de R$ 15.001')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='Range_salarial',
            field=models.CharField(blank=True, choices=[('Até R$ 1.000', 'Até R$ 1.000'), ('R$ 1.001 a R$ 3.000', 'R$ 1.001 a R$ 3.000'), ('R$ 3.001 a R$ 5.000', 'R$ 3.001 a R$ 5.000'), ('R$ 5.001 a R$ 7.000', 'R$ 5.001 a R$ 7.000'), ('R$ 7.001 a R$ 10.000', 'R$ 7.001 a R$ 10.000'), ('R$ 10.001 a R$ 15.000', 'R$ 10.001 a R$ 15.000'), ('Acima de R$ 15.001', 'Acima de R$ 15.001')], max_length=255, null=True),
        ),
    ]
