# Generated by Django 4.2.4 on 2023-08-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_aluno_renda_própria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_Nascimento',
            field=models.DateField(),
        ),
    ]
