# Generated by Django 4.2.4 on 2023-08-29 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_aluno_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='Data_Nascimento',
        ),
    ]
