# Generated by Django 4.2.4 on 2023-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_aluno_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='Responsavel',
        ),
        migrations.AddField(
            model_name='aluno',
            name='Escolaridade',
            field=models.CharField(blank=True, choices=[('Fundamental', 'Ensino Fundamental'), ('Medio', 'Ensino Médio'), ('Superior', 'Ensino Superior'), ('PosGraduacao', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='Range_salarial',
            field=models.CharField(blank=True, choices=[('Até R$ 1.000', 'Até R$ 1.000'), ('R$ 1.001 a R$ 3.000', 'R$ 1.001 a R$ 3.000'), ('R$ 3.001 a R$ 5.000', 'R$ 3.001 a R$ 5.000'), ('R$ 5.001 a R$ 7.000', 'R$ 5.001 a R$ 7.000'), ('R$ 7.001 a R$ 10.000', 'R$ 7.001 a R$ 10.000'), ('R$ 10.001 a R$ 15.000', 'R$ 10.001 a R$ 15.000'), ('Acima de R$ 15.001', 'Acima de R$ 15.001')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
